export let products = [
  {
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636895/2-labial5-mac_jzbyey.png",
    name: "Labial líquido Powder Kiss / MAC X L Hauste Pants",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636898/2-labial5_2-mac_esea6s.png",
    stock: 12,
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    marca: "mac cosmetics",
    category: "labios",
    id: "1ayeByKiYMOLtRu3dmxV",
  },
  {
    category: "joyeria",
    price: 710000,
    description:
      'El anillo "Fil de Camélia" es una joya exquisita de la colección de alta joyería de Chanel, inspirada en la icónica camelia, la flor favorita de Mademoiselle Coco Chanel. Este anillo refleja la elegancia y la sofisticación características de la marca, combinando diseño delicado y detalles refinados.',
    marca: "chanel",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722373387/anillo2-fil-chanel_yrhoew.png",
    name: "ANILLO FIL DE CAMÉLIA",
    stock: "11",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722373387/anillo-fil-chanel_vjrvnj.png",
    id: "5DneW6glwnrqfcvaWbDK",
  },
  {
    category: "rostro",
    price: 53000,
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637437/10-ilumindor-1_ym4rq7.png",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637440/10-ilumindor_aaunrm.png",
    description:
      "Este iluminador tiene una formula en polvo líquido que ilumina la piel y le da ese hermoso resplandor. También tiene una flor en relieve en el polvo y viene en el tono Show Gold, el color favorito de LISA, un rosa melocotón.",
    name: "Extra Dimension Skinfinish / MAC X L",
    marca: "mac cosmetics",
    stock: 6,
    id: "9qDUHk3TtPexhqcasTE0",
  },
  {
    price: 39000,
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721780847/gorro-icons-dior_un5qfx.png",
    marca: "dior",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721780848/gorro2-icons-dior_xuvwgp.png",
    description:
      "Este gorro Dior Icons, novedad de la temporada Primavera 2024, muestra el savoir-faire y los códigos de la Maison con un estilo sobrio y elegante. Se ha elaborado en cachemira azul marino jaspeada y destaca por su parche Dior con efecto ante en la parte",
    name: "Gorro Dior Icons",
    stock: 2,
    category: "cabeza",
    id: "IadD4wTLfPAtLMhTo0Ab",
  },
  {
    description:
      "El sombrero de pescador, novedad de la temporada Verano 2024, destaca por su atractivo atemporal. Se ha confeccionado en lana virgen texturizada azul marino y cuenta con un bordado Christian Dior Couture azul claro en el lateral.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721781689/sombrero-dior_yhr8cm.png",
    marca: "dior",
    name: "Sombrero de pescador Christian Dior Couture",
    category: "cabeza",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721781690/sombrero2-dior_uew8ud.png",
    stock: 6,
    price: 45000,
    id: "ImreP70D1EL3gTohU2xy",
  },
  {
    category: "joyerias",
    description:
      "Más que una flor, la camelia CHANEL es una fuente de inspiración. Sus curvas geométricas se prestan a una interminable variedad de estilos, desde los más naturalistas hasta los más abstractos.",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722371991/anillo2-camlia-chanel_ovzdgz.png",
    marca: "chanel",
    stock: 9,
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722371991/anillo-camlia-chanel_ev33xo.png",
    name: "Anillo Extrait de Camélia",
    price: 650000,
    id: "J0czi2QDxmp1nuX5P1Zc",
  },
  {
    name: "Labial líquido Powder Kiss / MAC X L Pink Roses",
    price: 37000,
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636624/2-labial4-mac_sfkhj4.png",
    marca: "mac cosmetics",
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636627/2-labial4_2-mac_va3khf.png",
    stock: 12,
    category: "labios",
    id: "LUIikKP6iw3JslVYIqsK",
  },
  {
    marca: "chanel",
    price: "1900000",
    stock: "12",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722373830/collar2-extrait-chanel_y3ec7b.png",
    category: "joyeria",
    description:
      'El collar "Extrait de Camélia" es una pieza excepcional de la colección de alta joyería de Chanel, que destaca por su diseño inspirado en la icónica flor de camelia, un símbolo recurrente en la obra de Mademoiselle Coco Chanel. Este collar encarna la elegancia y la sofisticación de la marca, combinando un diseño floral con un toque contemporáneo y lujoso.',
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722373830/collar-extrait-chanel_ffvara.png",
    name: "COLLAR EXTRAIT DE CAMÉLIA",
    id: "Nr3TPAEN2LYW7XxTpwVe",
  },
  {
    category: "joyeria",
    description:
      "Victoire de Castellane presenta la rosa en flor en la colección Rose Dior Couture, que simboliza una promesa de alegría futura. La nueva representación estilizada y sensual se ha inspirado en las rosas que han adornado los looks de alta costura diseñados por Christian Dior y sus sucesores",
    marca: "dior",
    stock: 10,
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722374197/collar2-rose-dior_wi3vnk.png",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722374198/collar-rose-dior_krjwfo.png",
    name: "Collar largo Rose Dior Couture",
    price: 12000000,
    id: "VdvsF5ZxUXOH1bSoVt0m",
  },
  {
    description:
      "Este rubor en el tono Melba, un coral melocotón, es el tono que usa habitualmente LISA y deja un sonrojo suave y natural en las mejillas.",
    name: "Rubor en polvo / MAC X L",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637250/9-rubor-1_r949cw.png",
    category: "rostro",
    stock: 12,
    marca: "mac cosmetics",
    price: 98280,
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637253/9-rubor_tb9syl.png",
    id: "WlGOPdxu0sNr7cPzPNqJ",
  },
  {
    price: "1200000",
    category: "calzado",
    description:
      "Las botas de piel de ternera negras de Chanel combinan la elegancia clásica con la modernidad sofisticada. Fabricadas con piel de alta calidad, estas botas destacan por su suavidad y durabilidad, ofreciendo un confort excepcional. El diseño presenta una silueta estilizada y atemporal, complementada con detalles icónicos de la marca, como el logo de Chanel discretamente grabado. Su versatilidad las hace perfectas tanto para ocasiones formales como informales, aportando un toque de lujo y distinción a cualquier conjunto.",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721784618/botas2-piel-chanel_hmupyo.png",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721784624/botas-piel-chanel_eowlzs.png",
    name: "Botas Piel de Ternera",
    "marca ": "chanel",
    stock: 6,
    id: "YftyDKWqO2t3fsTHAPeW",
  },
  {
    description:
      "Esta gorra presenta una silueta atemporal. Su diseño en lona de algodón negra incluye un bordado Christian Dior Couture tono sobre tono en la parte delantera. La prenda moderna y casual realzará cualquier conjunto informal.",
    stock: 7,
    marca: "dior",
    category: "cabeza",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721780607/gorra1-negra-dior_jpqeet.png",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1721780608/gorra2-negra-dior_ffcr8s.png",
    price: "40000",
    name: "Gorra Christian Dior Couture",
    id: "dm0vfeSNARuc2T5OmdPv",
  },
  {
    stock: 12,
    description:
      "La colección MAC X Lisa de MAC Cosmetics ha sido creada en colaboración con la artista femenina K-pop LISA integrante de la banda BLACKPINK Esta colección incluye cada uno de sus productos favoritos de LISA con tonos completamente nuevos inspirados en lo que más ama. La paleta de sombras, el rubor, el iluminador, los labiales así como los delineadores vienen en un envase morado brillante muy llamativo y bonito",
    category: "todo",
    price: 350000,
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719633914/1-colecci%C3%B3n-mac_v0yfvn.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719802899/1-colecci%C3%B3n-mac_2_qahbld.png",
    marca: "mac cosmetics",
    name: "Colección MAC X Lisa de MAC Cosmetics",
    id: "e23NMW9QRrARxqvBHdrD",
  },
  {
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635358/2-labial1-mac_gacghk.png",
    name: "Labial líquido Powder Kiss / MAC X L Swoon For Blooms",
    marca: "mac cosmetics",
    price: 37000,
    stock: 12,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    category: "labios",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635465/2-labial1_2-mac_xzku1r.png",
    id: "fPoDotBOBgYUscuMLhzS",
  },
  {
    name: "Labial líquido Powder Kiss / MAC X L Fashion, Sweetie",
    marca: "mac cosmetics",
    price: 37000,
    stock: 12,
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637084/2-labial6_2-mac_dvgec0.png",
    category: "labios",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637081/2-labial6-mac_z53lkt.png",
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    id: "jX2B37RkrQwsLIj5MbM2",
  },
  {
    price: 37000,
    marca: "mac cosmetics",
    category: "labios",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636425/2-labial3_2-mac_ae6oad.png",
    name: "Labial líquido Powder Kiss / MAC X L Rhythm 'N´ Roses",
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636270/2-labial3-mac_uxdnw0.png",
    stock: 12,
    id: "lW3rh8UViFnhm1337ZJe",
  },
  {
    " marca": "chanel",
    name: "PULCERA COCO CRUSH",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722372975/pulcera-coco-chanel_iftqzq.png",
    price: 10000000,
    stock: 12,
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722372975/pulcera2-coco-chanel_iz3h1r.png",
    description:
      'La pulsera "Coco Crush" de Chanel con diamantes es una pieza elegante y sofisticada que forma parte de la icónica colección de joyería de la marca. Inspirada en el emblemático motivo de acolchado que ha sido sinónimo de Chanel desde sus inicios, la pulsera presenta un diseño de líneas limpias y modernas, con un patrón en relieve que recuerda a los cojines de los bolsos clásicos de la marca.',
    category: "joyeria",
    id: "onOo25Noccg7BHXceN2R",
  },
  {
    marca: "mac cosmetics",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634613/2-sombra2-mac_ha6w7f.png",
    price: 71000,
    stock: 12,
    name: "Paleta de sombras de ojos M·A·C X L",
    description:
      "La paleta incluye desde tonos brillantes inspirados en el sabor de helado favorito de LISA hasta sombras con el nombre de sus gatos. La combinación de neutros con tonos vibrantes es muy hermosa y versátil, también cuenta con diferentes acabados, desde mates hasta purpurinas. La selección de colores es preciosa con tonos que se pueden usar para cualquier momento y ocasión.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634398/2-sombra-mac_zkabik.png",
    category: "ojos",
    id: "rC11IQGLnCzSPALOPTLq",
  },
  {
    name: "Delineador de ojos Brushstroke 24-Hour / MAC X L",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634888/3-deliniador-mac_eosqsl.png",
    img3: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635075/3-deliniadorcolor2-mac_gx47cq.png",
    price: 33000,
    stock: 9,
    description:
      "Este delineador de ojos líquido viene en un envase morado metálico y esta disponible en 2 tonos, marrón y negro.",
    category: "ojos",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634991/3-deliniadorcolor1-mac_wpwoct.png",
    marca: "mac cosmetics",
    id: "rDcVOGWxnY7YmErkLAFh",
  },
  {
    category: "labios",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636158/2-labial2_2-mac_w10o9m.png",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635785/2-labial2-mac_werl7b.png",
    price: 37000,
    name: "Labial líquido Powder Kiss / MAC X L Sorry Not Sorry",
    stock: 12,
    marca: "mac cosmetics",
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    id: "tdkpovRr3B1jS3c6jstB",
  },
  {
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722374723/anillo2-cout-dior_zwljqw.png",
    price: 900000,
    category: "joyeria",
    name: "Anillo grande Rose Dior Couture",
    marca: "dior",
    stock: 10,
    description:
      "Victoire de Castellane presenta la rosa en flor en la colección Rose Dior Couture, que simboliza una promesa de alegría futura. La nueva representación estilizada y sensual se ha inspirado en las rosas que han adornado los looks de alta costura diseñados por Christian Dior y sus sucesores.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1722374723/anillo-cout-dior_oov2mg.png",
    id: "ucp2KnCtKXiTxvHAg24e",
  },
];
