export let products = [
  {
    id: 1,
    name: "Colección MAC X Lisa de MAC Cosmetics",
    marca: "mac cosmetics",
    price: 350000,
    description:
      "La colección MAC X Lisa de MAC Cosmetics ha sido creada en colaboración con la artista femenina K-pop LISA integrante de la banda BLACKPINK Esta colección incluye cada uno de sus productos favoritos de LISA con tonos completamente nuevos inspirados en lo que más ama. La paleta de sombras, el rubor, el iluminador, los labiales así como los delineadores vienen en un envase morado brillante muy llamativo y bonito",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719633914/1-colecci%C3%B3n-mac_v0yfvn.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719802899/1-colecci%C3%B3n-mac_2_qahbld.png",
    stock: 12,
    category: "todo",
  },
  {
    id: 2,
    name: "Paleta de sombras de ojos M·A·C X L",
    marca: "mac cosmetics",
    price: 71000,
    description:
      "La paleta incluye desde tonos brillantes inspirados en el sabor de helado favorito de LISA hasta sombras con el nombre de sus gatos. La combinación de neutros con tonos vibrantes es muy hermosa y versátil, también cuenta con diferentes acabados, desde mates hasta purpurinas. La selección de colores es preciosa con tonos que se pueden usar para cualquier momento y ocasión.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634398/2-sombra-mac_zkabik.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634613/2-sombra2-mac_ha6w7f.png",
    stock: 12,
    category: "ojos",
  },
  {
    id: 3,
    name: "Delineador de ojos Brushstroke 24-Hour / MAC X L",
    marca: "mac cosmetics",
    price: 33000,
    description:
      "Este delineador de ojos líquido viene en un envase morado metálico y esta disponible en 2 tonos, marrón y negro.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634888/3-deliniador-mac_eosqsl.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719634991/3-deliniadorcolor1-mac_wpwoct.png",
    img3: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635075/3-deliniadorcolor2-mac_gx47cq.png",
    stock: 12,
    category: "ojos",
  },
  {
    id: 4,
    name: "Labial líquido Powder Kiss / MAC X L Swoon For Blooms",
    marca: "mac cosmetics",
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635358/2-labial1-mac_gacghk.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635465/2-labial1_2-mac_xzku1r.png",
    stock: 12,
    category: "labios",
  },
  {
    id: 5,
    name: "Labial líquido Powder Kiss / MAC X L Sorry Not Sorry",
    marca: "mac cosmetics",
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719635785/2-labial2-mac_werl7b.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636158/2-labial2_2-mac_w10o9m.png",
    stock: 12,
    category: "labios",
  },
  {
    id: 6,
    name: "Labial líquido Powder Kiss / MAC X L Rhythm 'N´ Roses",
    marca: "mac cosmetics",
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636270/2-labial3-mac_uxdnw0.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636425/2-labial3_2-mac_ae6oad.png",
    stock: 12,
    category: "labios",
  },
  {
    id: 7,
    name: "Labial líquido Powder Kiss / MAC X L Pink Roses",
    marca: "mac cosmetics",
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636624/2-labial4-mac_sfkhj4.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636627/2-labial4_2-mac_va3khf.png",
    stock: 12,
    category: "labios",
  },
  {
    id: 8,
    name: "Labial líquido Powder Kiss / MAC X L Hauste Pants",
    marca: "mac cosmetics",
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636895/2-labial5-mac_jzbyey.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719636898/2-labial5_2-mac_esea6s.png",
    stock: 12,
    category: "labios",
  },
  {
    id: 9,
    name: "Labial líquido Powder Kiss / MAC X L Fashion, Sweetie",
    marca: "mac cosmetics",
    price: 37000,
    description:
      "Este labial líquido no solo tiene una textura cremosa sino que proporciona una hidratación suave y un color uniforme duradero y sensual. Hay 6 tonos disponibles.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637081/2-labial6-mac_z53lkt.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637084/2-labial6_2-mac_dvgec0.png",
    stock: 12,
    category: "labios",
  },
  {
    id: 10,
    name: "Rubor en polvo / MAC X L",
    marca: "mac cosmetics",
    price: 98280,
    description:
      "Este rubor en el tono Melba, un coral melocotón, es el tono que usa habitualmente LISA y deja un sonrojo suave y natural en las mejillas.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637253/9-rubor_tb9syl.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637250/9-rubor-1_r949cw.png",
    stock: 12,
    category: "rostro",
  },
  {
    id: 11,
    name: "Extra Dimension Skinfinish / MAC X L",
    marca: "mac cosmetics",
    price: 53000,
    description:
      "Este iluminador tiene una formula en polvo líquido que ilumina la piel y le da ese hermoso resplandor. También tiene una flor en relieve en el polvo y viene en el tono Show Gold, el color favorito de LISA, un rosa melocotón.",
    img: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637440/10-ilumindor_aaunrm.png",
    img2: "https://res.cloudinary.com/dlmljdft1/image/upload/v1719637437/10-ilumindor-1_ym4rq7.png",
    stock: 12,
    category: "rostro",
  },
];
